name = "github-actions-examples"
compatibility_date = "2024-09-29"
compatibility_flags = [ "nodejs_compat" ]
main = "src/index.ts"

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "KV"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "github-actions-sample"
database_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [ai]
# binding = "AI"