service:
  name: github-actions-examples
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello

  api:
    handler: handler.api
    events:
      - http: ANY /
      - http: ANY /{proxy+}
