# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'github-actions-examples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for github-actions-examples

  target 'github-actions-examplesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'github-actions-examplesUITests' do
    # Pods for testing
  end

end
