# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

USE_XCODE_VERSION = "11.5"

default_platform(:ios)

platform :ios do
  before_all do
    cocoapods
  end

  desc "Distribution of AppStore build"
  lane :store_build  do |options|
    select_xcode
    update_team
    configuration = 'Release'
    if options[:configuration]
      configuration = options[:configuration]
    end
    build_app({
      configuration: configuration,
      scheme: "github-actions-examples",
      export_method: "app-store",
      output_name: "github-actions-examples-store-#{configuration.downcase}.ipa",
      include_bitcode: true,
      clean: true,
    })
  end

  desc "Distribution of AdHoc build"
  lane :adhoc_build do |options|
    select_xcode
    update_team
    configuration = 'Debug'
    if options[:configuration]
      configuration = options[:configuration]
    end
    build_app(
      configuration: configuration,
      scheme: "github-actions-examples",
      export_method: 'ad-hoc',
      export_xcargs: '-allowProvisioningUpdates',
      output_name: "github-actions-examples-adhoc-#{configuration.downcase}.ipa",
      include_bitcode: true,
      clean: true
    )
  end

  private_lane :update_team do |options|
    #update_project_team(
    #  path: "github-actions-examples.xcodeproj",
    #  teamid: ENV.fetch("TEAM_ID") { "TEAM_ID" }
    #)
  end

  desc "select common xcode version"
  private_lane :select_xcode do
    xcversion(version: USE_XCODE_VERSION)
  end
end
