# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    cocoapods
  end

  desc "execute debug build"
  lane :debug_build do
    build_app(scheme: "github-actions-examples",
      include_bitcode: true)
  end

  desc "execute release build by gym"
  lane :release_build do
    gym(scheme: "github-actions-examples")
  end
end
