name: Android Debug Build

on:
  push:
    branches:
    - android-build

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        compile-sdk: [31]
        build-tools: [30.0.3]

    steps:
    - uses: actions/checkout@v2
    - name: setup ubuntu
      run: |
        sudo apt-get --quiet update --yes
        sudo apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
    - name: setup JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: download Android SDK
      working-directory: ./Android
      run: |
        wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip -d android-sdk-unziped android-sdk.zip
        sudo mkdir -p /root/.android
        sudo touch /root/.android/repositories.cfg
        sudo mv android-sdk-unziped/cmdline-tools android-sdk-linux/cmdline-tools/latest
        echo y | android-sdk-linux/cmdline-tools/latest/bin/sdkmanager "platforms;android-${{ matrix.compile-sdk }}" >/dev/null
        echo y | android-sdk-linux/cmdline-tools/latest/bin/sdkmanager "platform-tools" >/dev/null
        echo y | android-sdk-linux/cmdline-tools/latest/bin/sdkmanager "build-tools;${{ matrix.build-tools }}" >/dev/null
        export ANDROID_HOME=$PWD/android-sdk-linux
        export PATH=$PATH:$PWD/android-sdk-linux/cmdline-tools/latest/platform-tools/
        chmod +x ./gradlew
        set +o pipefail
        yes | android-sdk-linux/cmdline-tools/latest/bin/sdkmanager --licenses
        set -o pipefail
    - name: Android Debug Build
      working-directory: ./Android
      run: ./gradlew assembleDebug
    - uses: actions/upload-artifact@master
      with:
        name: outputs
        path: Android/app/build/outputs/