name: Android CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        compile-sdk: [29]
        build-tools: [29.0.2]
        sdk-tools:   [4333796]

    steps:
    - uses: actions/checkout@v1
    - name: setup ubuntu
      run: |
        apt-get --quiet update --yes
        apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
    - name: setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: setup Android SDK
      run: |
        wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${{ matrix.compile-sdk }}.zip
        unzip -d android-sdk-linux android-sdk.zip
        mkdir -p /root/.android
        touch /root/.android/repositories.cfg
        echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${{ matrix.build-tools }}" >/dev/null
        echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
        echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${{ matrix.sdk-tools }}" >/dev/null
        export ANDROID_HOME=$PWD/android-sdk-linux
        export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
        chmod +x ./gradlew
        set +o pipefail
        yes | android-sdk-linux/tools/bin/sdkmanager --licenses
        set -o pipefail
    - name: Android Debug Build
      run: ./gradlew assembleDebug
      with: build