name: Android Release Build And Test Run

on:
  push:
    branches:
    - android-test

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        compile-sdk: [31]
        build-tools: [30.0.3]
        test-device-model-name: ["Pixel3"]
        test-device-version: [30]
        test-locale: ["ja_JP"]

    steps:
    - uses: actions/checkout@v3
    - name: setup ubuntu
      run: |
        sudo apt-get --quiet update --yes
        sudo apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
    - uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.FIREBASE_CREDENTIALS_JSON }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: gcloud update latest compoments
      run: gcloud components update
    - name: setup JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: download Android SDK
      working-directory: ./Android
      run: |
        wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
        unzip -d android-sdk-linux android-sdk.zip
        sudo mkdir -p /root/.android
        sudo touch /root/.android/repositories.cfg
        echo y | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. "platforms;android-${{ matrix.compile-sdk }}" >/dev/null
        echo y | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. "platform-tools" >/dev/null
        echo y | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. "build-tools;${{ matrix.build-tools }}" >/dev/null
        export ANDROID_SDK_ROOT=$PWD
        export PATH=$PATH:$PWD/platform-tools/
        chmod +x ./gradlew
        set +o pipefail
        yes | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. --licenses
        set -o pipefail
    - name: setup google-services.json
      working-directory: ./Android
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: |
        echo "${GOOGLE_SERVICES_JSON}" >> ./app/google-services.json
    - name: Android Debug Apk Build
      working-directory: ./Android
      run: ./gradlew assembleDebug
    - name: Android Debug Test Apk Build
      working-directory: ./Android
      run: ./gradlew assembleDebugAndroidTest
    - name: Set execute project id
      run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}
    - name: Execute firebase robo test
      working-directory: ./Android
      run: gcloud firebase test android run --type robo --app app/build/outputs/apk/debug/app-debug.apk --device "model=${{ matrix.test-device-model-name }},version=${{ matrix.test-device-version }},locale=${{ matrix.test-locale }}"
    - name: Execute firebase instrumentation test
      working-directory: ./Android
      run: gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --device "model=${{ matrix.test-device-model-name }},version=${{ matrix.test-device-version }},locale=${{ matrix.test-locale }}"