name: Android Debug Build

on:
  push:
    branches:
    - android-build

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        compile-sdk: [35]
        build-tools: [35.0.0]
        commandlinetools-download-url: ['https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip']
        root-project-path: [./Android]

    steps:
    - uses: actions/checkout@v4
    - name: setup ubuntu
      run: |
        sudo apt-get --quiet update --yes
        sudo apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
    - name: setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'
    - name: download Android SDK
      working-directory: ${{ matrix.root-project-path }}
      run: |
        wget --quiet --output-document=android-sdk.zip ${{ matrix.commandlinetools-download-url }}
        unzip -d android-sdk-linux android-sdk.zip
        sudo mkdir -p /root/.android
        sudo touch /root/.android/repositories.cfg
        echo y | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. "platforms;android-${{ matrix.compile-sdk }}" >/dev/null
        echo y | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. "platform-tools" >/dev/null
        echo y | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. "build-tools;${{ matrix.build-tools }}" >/dev/null
        export ANDROID_SDK_ROOT=$PWD
        export PATH=$PATH:$PWD/platform-tools/
        chmod +x ./gradlew
        set +o pipefail
        yes | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. --licenses
        set -o pipefail
    - name: setup google-services.json
      working-directory: ${{ matrix.root-project-path }}
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: |
        echo "${GOOGLE_SERVICES_JSON}" >> ./app/google-services.json
    - name: Android Debug Build
      working-directory: ${{ matrix.root-project-path }}
      run: ./gradlew assembleDebug
    - uses: actions/upload-artifact@v4
      with:
        name: outputs
        path: ${{ matrix.root-project-path }}/app/build/outputs/