name: Android Release Build

on:
  push:
    branches:
    - android-build

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        compile-sdk: [31]
        build-tools: [30.0.3]
        sdk-tools-url: [https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip]

    steps:
    - uses: actions/checkout@v2
    - name: setup ubuntu
      run: |
        sudo apt-get --quiet update --yes
        sudo apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
    - name: setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: download Android SDK
      working-directory: ./Android
      run: |
        wget --quiet --output-document=android-sdk.zip ${{ matrix.sdk-tools-url }}
        unzip -d android-sdk-linux android-sdk.zip
        sudo mkdir -p /root/.android
        sudo touch /root/.android/repositories.cfg
        echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${{ matrix.compile-sdk }}" >/dev/null
        echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
        echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${{ matrix.build-tools }}" >/dev/null
        export ANDROID_HOME=$PWD/android-sdk-linux
        export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
        chmod +x ./gradlew
        set +o pipefail
        yes | android-sdk-linux/tools/bin/sdkmanager --licenses
        set -o pipefail
    - name: Setup Build Configs
      working-directory: ./Android
      env:
        ANDROID_REALSE_BASE64_KEY: ${{ secrets.ANDROID_REALSE_BASE64_KEY }}
        ANDROID_REALSE_KEY_PASSWORD: ${{ secrets.ANDROID_REALSE_KEY_PASSWORD }}
      run: |
        echo ${ANDROID_REALSE_BASE64_KEY} | base64 -d > ./release-application-key
        echo "RELEASE_STORE_FILE=`pwd`/release-application-key" >> ./local.properties
        echo "RELEASE_STORE_PASSWORD=${ANDROID_REALSE_KEY_PASSWORD}" >> ./local.properties
        echo "RELEASE_KEY_ALIAS=key0" >> ./local.properties
        echo "RELEASE_KEY_PASSWORD=${ANDROID_REALSE_KEY_PASSWORD}" >> ./local.properties
    - name: Android Release Apk Build
      working-directory: ./Android
      run: ./gradlew assembleRelease
    - name: Android Release aab Build
      working-directory: ./Android
      run: ./gradlew bundleRelease
    - uses: actions/upload-artifact@v2
      with:
        name: outputs
        path: Android/app/build/outputs/
  distribution:
    name: AppDistribution
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: outputs
          path: Android/outputs
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          file: Android/outputs/apk/release/app-release.apk