name: Android Release Build And Test Run

on:
  push:
    branches:
    - android-test

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        compile-sdk: [31]
        build-tools: [30.0.3]

    steps:
    - uses: actions/checkout@v2
    - name: setup ubuntu
      run: |
        sudo apt-get --quiet update --yes
        sudo apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
    - name: download gcloud sdk
      working-directory: ./Android
      run: |
        curl --output google-cloud-sdk.tar.gz -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-380.0.0.0-linux-x86_64.tar.gz
        tar xvzf google-cloud-sdk.tar.gz
    - name: download gcloud sdk
      working-directory: ./Android
      run: |
        ./google-cloud-sdk/install.sh
    - name: gcloud components update
      working-directory: ./Android
      run: |
        ./google-cloud-sdk/bin/gcloud init --skip-diagnostics
    - name: gcloud auth login
      working-directory: ./Android
      run: |
         gcloud auth login
    - name: setup JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: download Android SDK
      working-directory: ./Android
      run: |
        wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
        unzip -d android-sdk-linux android-sdk.zip
        sudo mkdir -p /root/.android
        sudo touch /root/.android/repositories.cfg
        echo y | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. "platforms;android-${{ matrix.compile-sdk }}" >/dev/null
        echo y | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. "platform-tools" >/dev/null
        echo y | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. "build-tools;${{ matrix.build-tools }}" >/dev/null
        export ANDROID_SDK_ROOT=$PWD
        export PATH=$PATH:$PWD/platform-tools/
        chmod +x ./gradlew
        set +o pipefail
        yes | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=. --licenses
        set -o pipefail
    - name: Setup Build Configs
      working-directory: ./Android
      env:
        ANDROID_REALSE_BASE64_KEY: ${{ secrets.ANDROID_REALSE_BASE64_KEY }}
        ANDROID_REALSE_KEY_PASSWORD: ${{ secrets.ANDROID_REALSE_KEY_PASSWORD }}
      run: |
        echo ${ANDROID_REALSE_BASE64_KEY} | base64 -d > ./release-application-key
        echo "RELEASE_STORE_FILE=`pwd`/release-application-key" >> ./local.properties
        echo "RELEASE_STORE_PASSWORD=${ANDROID_REALSE_KEY_PASSWORD}" >> ./local.properties
        echo "RELEASE_KEY_ALIAS=key0" >> ./local.properties
        echo "RELEASE_KEY_PASSWORD=${ANDROID_REALSE_KEY_PASSWORD}" >> ./local.properties
    - name: Android Release Apk Build
      working-directory: ./Android
      run: ./gradlew assembleRelease