name: Firebase Hostings Deploy

on:
  push:
    branches:
    - firebase-deploy

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        root-project-path: [./firebase]

    steps:
      - uses: actions/checkout@v2
      - name: setup ubuntu
        run: sudo apt-get --quiet update --yes
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        working-directory: ${{ matrix.root-project-path }}/firebase-hosting-example
        run: |
          yarn install
      - name: yarn build
        working-directory: ${{ matrix.root-project-path }}/firebase-hosting-example
        run: |
          yarn run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: hosting-build
          path: ${{ matrix.root-project-path }}/firebase-hosting-example/public
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: hosting-build
          path: ${{ matrix.root-project-path }}/public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ${{ matrix.root-project-path }}