name: iOS Release Build

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode-version: [11.5]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Bundle Install
      working-directory: ./iOS
      run: bundle install
    - name: Select Xcode version
      working-directory: ./iOS
      run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode-version }}.app'
    - name: Show Xcode version
      working-directory: ./iOS
      run: xcodebuild -version