name: iOS Store Build

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode-version: [11.5]
        build-configuration: [Release]
        provisioning-profile-filepath: [githubactionsexamplesstorebuild20200531.mobileprovision]
        build-scheme: [github-actions-examples]
        xcodeproject-path: [github-actions-examples.xcodeproj]
        keychain-name: [github-actions-examples-chain]
        certificate-path: [ios_distribution.p12]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Bundle Install
      working-directory: ./iOS
      run: bundle install
    - name: Select Xcode version
      working-directory: ./iOS
      run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode-version }}.app'
    - name: Show Xcode version
      working-directory: ./iOS
      run: xcodebuild -version
    - name: Decode base64 p12 iOS Build key
      working-directory: ./iOS
      env:
        IOS_DISTRIBUTION_CERTIFICATE_P12_FILE_BASE64: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE_P12_FILE_BASE64 }}
      run: |
        echo ${IOS_DISTRIBUTION_CERTIFICATE_P12_FILE_BASE64} | base64 -d > ./ios_distribution.p12
    - name: Decode base64 provisioning profile
      working-directory: ./iOS
      env:
        IOS_STORE_MOBILEPROVISION_FILE_BASE64: ${{ secrets.IOS_STORE_MOBILEPROVISION_FILE_BASE64 }}
      run: |
        echo ${IOS_STORE_MOBILEPROVISION_FILE_BASE64} | base64 -d > ./${{ matrix.provisioning-profile-filepath }}
    - name: Setup Fastlane Build .env
      working-directory: ./iOS
      env:
        KEYCHAIN_PASSWORD: ${{ secrets.IOS_DISTRIBUTION_KEYCHAIN_PASSWORD }}
        CERT_PASSWORD: ${{ secrets.IOS_DISTRIBUTION_CERT_PASSWORD }}
      run: |
        echo "KEYCHAIN_PASSWORD=${KEYCHAIN_PASSWORD}" >> ./fastlane/.env
        echo "CERT_PASSWORD=${CERT_PASSWORD}" >> ./fastlane/.env
    - name: execute fastlane ios build
      working-directory: ./iOS
      run: bundle exec fastlane ios store_build scheme:${{ matrix.build-scheme }} xcode_version:${{ matrix.xcode-version }} configuration:${{ matrix.build-configuration }} provisioning_profile:${{ matrix.provisioning-profile-filepath }} xcodeproject_path:${{ matrix.xcodeproject-path }} team_id:${{ secrets.IOS_TEAM_ID }} keychain_name:${{ matrix.keychain-name }} certificate_path:${{ matrix.certificate-path }} create_new_keychain:true --verbose
    - uses: actions/upload-artifact@master
      with:
        name: result
        path: iOS/${{ matrix.build-scheme }}-store-${{ matrix.build-configuration }}.ipa