on: [push]

name: Serverless Deploy
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: setup ubuntu
      run: sudo apt-get --quiet update --yes
    - name: yarn install
      working-directory: ./serverless
      run: yarn install
    - name: serverless package and deploy
      working-directory: ./serverless
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        yarn add serverless
        ./node_modules/serverless/bin/serverless package --package ./build
        ./node_modules/serverless/bin/serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
        ./node_modules/serverless/bin/serverless deploy --package ./build
    - uses: actions/upload-artifact@master
      with:
        name: build
        path: serverless/build