on:
  push:
    branches:
    - server-deploy

name: Serverless Deploy
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: setup ubuntu
      run: sudo apt-get --quiet update --yes
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      working-directory: ./serverless
      run: yarn install
    - name: yarn serverless build package
      working-directory: ./serverless
      run: yarn run serverless package --package ./build
    - name: serverless deploy
      working-directory: ./serverless
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        yarn run serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
        yarn run serverless deploy --package ./build
    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: serverless/build