on: [push]

name: Serverless Deploy
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: change root directory
      run: cd serverless
    - name: yarn install
      working-directory: ./serverless
      run: yarn install
    - name: setup aws access-key
      working-directory: ./serverless
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - name: serverless package
      working-directory: ./serverless
      run: yarn run serverless package --package ./build
    - name: serverless deploy
      working-directory: ./serverless
      run: yarn run serverless deploy --package ./build
    - uses: actions/upload-artifact@master
      with:
        name: build
        path: serverless/build