on: [push]

name: Serverless Deploy
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: change root directory
      run: cd serverless
    - name: npm install
      uses: actions/npm@master
      with:
        entrypoint: ./serverless
        args: install
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        entrypoint: ./serverless
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}