name: Build project

on: [push]

jobs:
  buildForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - Unity/
        unityVersion:
          - 2019.2.11f1
        targetPlatform:
          - WebGL
    steps:
      - uses: actions/checkout@v2
      - name: setup ubuntu
        run: |
          sudo apt-get --quiet update --yes
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: webbertakken/unity-request-manual-activation-file@v1.1
        with:
          unityVersion: ${{ matrix.unityVersion }}
      - uses: pCYSl5EDgo/cat@master
        id: license
        with:
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
      - uses: webbertakken/unity-builder@v1.0
        env:
          UNITY_LICENSE: ${{ steps.license.outputs.text }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build