name: Unity Create ALF
on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        unity-tag: [2019.4.14f1]
    container: docker://gableroux/unity3d:${{ matrix.unity-tag }}

    steps:
    - uses: actions/checkout@v2
    - name: setup ubuntu
      run: |
        sudo apt-get --quiet update --yes
        sudo apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
    - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -logfile -createManualActivationFile || exit 0
    - uses: actions/upload-artifact@master
      with:
        name: "Unity_v${{ matrix.unity-tag }}.alf"
        path: artifact