name: execute-unity-annothor-os-build
on:
  push:
    branches:
    - feature/research-unity-build
jobs:
  build:
    name: build
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        unity-editor-version: [2021.3.4f1]
        unity-license-version: [2021.x]
        node-version: [14.x]
        root-project-path: [Unity]
        unity-editor-install-path: [UnityEditor]
        unity-module:
          #- android
          #- webgl
          - windows-il2cpp
        targetPlatform:
          #- StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          #- StandaloneWindows64 # Build a Windows 64-bit standalone.
          #- StandaloneLinux64 # Build a Linux 64-bit standalone.
          #- iOS # Build an iOS player.
          #- Android # Build an Android .apk standalone app.
          #- WebGL # WebGL.
    steps:
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Cache
      - uses: actions/cache@v3
        id: cache-unity-editor
        with:
          key: ${{ runner.os }}-Unity-Editor-${{ matrix.unity-editor-version }}
          path: ${{ matrix.unity-editor-install-path }}\${{ matrix.unity-editor-version }}
          restore-keys: ${{ runner.os }}-Unity-Editor-${{ matrix.unity-editor-version }}-

      # Cache
      - uses: actions/cache@v3
        id: cache-unity-library
        with:
          key: ${{ runner.os }}-Unity-Library-${{ matrix.targetPlatform }}
          path: ${{ matrix.root-project-path }}\Library
          restore-keys: ${{ runner.os }}-Unity-Library-

      # Cache
      - uses: actions/cache@v3
        id: cache-unity-license
        with:
          key: ${{ runner.os }}-Unity-License-${{ matrix.unity-license-version }}
          path: |
            ${{ matrix.root-project-path }}/Unity_v${{ matrix.unity-license-version }}.ulf
            ${{ matrix.root-project-path }}/Unity_v${{ matrix.unity-editor-version }}.alf

      - if: ${{ steps.cache-unity-editor.outputs.cache-hit == 'false' }}
        name: Setup Unity
        id: setup-unity
        uses: kuler90/setup-unity@v1.0.8
        with:
          unity-version: ${{ matrix.unity-editor-version }}
          unity-modules: ${{ matrix.unity-module }}
          install-path: ${{ github.workspace }}\${{ matrix.unity-editor-install-path }}
      - name: Print output
        run: |
          echo unity-version: ${{ steps.setup-unity.outputs.unity-version }}
          echo unity-path: ${{ steps.setup-unity.outputs.unity-path }}
          echo env UNITY_PATH: ${{ env.UNITY_PATH }}
          echo workspace path: ${{ github.workspace }}
      - name: generate alf file
        working-directory: ${{ matrix.root-project-path }}
        run: |
          ${{ matrix.unity-editor-install-path }}\${{ matrix.unity-editor-version }}\Editor\Unity.exe -batchmode -nographic -quit -createManualActivationFile -logfile
      - name: Activate Unity
        uses: kuler90/activate-unity@v1
        with:
          unity-path: ${{ steps.setup-unity.outputs.unity-path }}
          unity-username: ${{ secrets.UNITY_EMAIL }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-authenticator-key: ${{ secrets.UNITY_AUTHENTICATOR_KEY }}
          unity-serial: ${{ secrets.UNITY_SERIAL }}
      - name: check
        working-directory: ${{ matrix.root-project-path }}
        run: dir
      - name: check
        run: dir
      # Activate from alf File
#      - name: Install node package, `unity-activate`
#        run: npm install -g unity-activate
#      - name: Activate The License
#        id: activateLicense
#        run: unity-activate -u "${{ secrets.UNITY_EMAIL }}" -p "${{ secrets.UNITY_PASSWORD }}" -k "${{ secrets.UNITY_AUTHENTICATOR_KEY }}" -o ${{ matrix.root-project-path }}/ -s ${{ secrets.UNITY_SERIAL }} "${{ steps.getManualLicenseFile.outputs.filePath }}"
      # Upload Build
      - name: Upload alfFile
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}

      # Upload Build
      - name: Upload ulfFile
        uses: actions/upload-artifact@v3
        with:
          name: Unity_v${{ matrix.unity-license-version }}.ulf
          path: ${{ matrix.root-project-path }}/Unity_v${{ matrix.unity-license-version }}.ulf

      - name: Read ulf
        id: ulfRead
        uses: juliangruber/read-file-action@v1
        with:
          path: ./Unity_v${{ matrix.unity-license-version }}.ulf

      # Build
      - name: Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ steps.ulfRead.outputs.content }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: ${{ matrix.root-project-path }}
          unityVersion: ${{ matrix.unity-editor-version }}
          allowDirtyBuild: true

      # Upload Build
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: Build-Results
          path: build/