name: Acquire activation file
on: [push]
jobs:
  activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unity-tag: [2020.3.26f1]
    steps:
    - name: Request manual activation file
      id: getManualLicenseFile
      uses: game-ci/unity-request-activation-file@v2
      with:
        unityVersion: ${{ matrix.unity-tag }}
    - name: check
      run: ls -a
    - name: Expose as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.getManualLicenseFile.outputs.filePath }}
        path: ${{ steps.getManualLicenseFile.outputs.filePath }}